services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/auth
      - REACT_APP_MOCK_AUTH=false
    depends_on:
      - backend
    volumes:
      - ./web:/app 
      - /app/node_modules

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ES_HOST=http://elasticsearch:9200
      - BM25_INDEX_NAME=quy_che_index
      - BM25_DATA_PATH=data/final.csv
      - BM25_TOP_K=5
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - elasticsearch
    volumes:
      - ./server:/app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local
